version: "3.8"
networks:
  app-tier:
    driver: bridge

services:
  mysql:
    hostname: mysql
    image: mysql:8.0.27
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/database
    ports:
      - ${MYSQL_PORT}:3306
    expose:
      - 3306
    networks:
      - app-tier
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_TCP_PORT: 3306

    env_file: ./.env

  backend:
    depends_on:
      - mysql
    build:
      context: ./backend

    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    restart: always
    ports:
      - ${BACKEND_PORT}:5000
    networks:
      - app-tier
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    env_file: ./.env

  frontend:
    depends_on:
      - backend
      - mysql
    build:
      context: ./frontend
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
    ports:
      - ${FRONTEND_PORT}:3000
    networks:
      - app-tier
    env_file: ./.env

volumes:
  db_data: {}
